# Generated by Django 5.1.4 on 2025-01-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
